### ISSUE TITLE
Trouble in Windows

### ISSUE THREAD

**Issue by erpcfe** [erlang-ls/vscode#57]
I have a problem in Windows, the compiler diagnostic does not work and the extension in general does not work showing me an error.
<img width="960" alt="test" src="https://user-images.githubusercontent.com/60412061/95638030-6060e380-0a61-11eb-8b7f-5eee513fe9d3.png">

This happens to me from version 0.0.12 onwards, in version 0.0.11 everything was fine except for the compiler diagnosis that did not display errors or warnings.

Would someone give me an advice to try to solve it?

**Comment by robertoaloi** [comment]
Hi @erpcfe ,

Unfortunately Windows support is currently best-effort, since we don't have a CI pipeline for Windows and it's easy to introduce regressions during development in such a case. See the work started in https://github.com/erlang-ls/erlang_ls/pull/686
Maybe you have some server side logs that we could look at to troubleshoot the issue? See [here](https://erlang-ls.github.io/troubleshooting/#logging) where to find them.

**Comment by erpcfe** [comment]
Thanks it helped me a lot, I solved most of the problems.
The only thing that doesn't work is the "compiler diagnostic", this is my configuration file:
<img width="361" alt="config" src="https://user-images.githubusercontent.com/60412061/96268196-c1734480-0f96-11eb-8fba-ff57388debdf.png">
